/**
 * File name: src/admin/AdminOffers.jsx
 * Purpose: Offer CRUD manager for public promotions.
 * Contains: Create/update offer form, offer cards, active toggle, edit, and delete actions.
 * Used by: Route /admin/offers.
 * Future edits: Add coupon codes, expiration dates, or featured offer controls here.
 */
import { useState } from 'react';
import { adminApi } from '../api/adminApi';
import { useAdminResource } from '../hooks/useAdminResource';
import AdminPageHeader from '../components/AdminPageHeader.jsx';
import FormField from '../components/FormField.jsx';
import LoadingSpinner from '../components/LoadingSpinner.jsx';
const blank={title:'',subtitle:'',description:'',badge:'',isActive:true};
export default function AdminOffers(){ const {data,loading,refresh}=useAdminResource(adminApi.offers); const [form,setForm]=useState(blank); const [editing,setEditing]=useState(null); async function save(e){ e.preventDefault(); if(editing) await adminApi.updateOffer(editing,form); else await adminApi.createOffer(form); setForm(blank); setEditing(null); refresh(); } function edit(o){ setEditing(o._id); setForm({title:o.title||'',subtitle:o.subtitle||'',description:o.description||'',badge:o.badge||'',isActive:o.isActive!==false}); } async function remove(id){ if(confirm('Delete this offer?')){ await adminApi.deleteOffer(id); refresh(); } } return <section><AdminPageHeader title="Offers" subtitle="Manage discounts, loyalty offers, referral promos, and monthly specials."/><form onSubmit={save} className="mb-6 grid gap-4 rounded-3xl border border-blush bg-white p-5 shadow-soft md:grid-cols-2"><FormField label="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><FormField label="Badge" value={form.badge} onChange={e=>setForm({...form,badge:e.target.value})} placeholder="First Visit / Popular / Monthly"/><FormField label="Subtitle" value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})}/><FormField as="textarea" label="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="min-h-24"/><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active</label><div className="flex gap-2 md:justify-end"><button className="rounded-2xl bg-brown px-5 py-3 font-black text-white">{editing?'Update Offer':'Add Offer'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(blank)}} className="rounded-2xl bg-stone-100 px-5 py-3 font-black text-brown">Cancel</button>}</div></form>{loading?<LoadingSpinner/>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.map(o=><div key={o._id} className="rounded-3xl border border-blush bg-white p-5 shadow-soft"><span className="rounded-full bg-gold/10 px-3 py-1 text-xs font-black text-gold">{o.badge||'Offer'}</span><h3 className="mt-3 text-xl font-black text-brown">{o.title}</h3><p className="mt-1 font-bold text-rose">{o.subtitle}</p><p className="mt-2 text-sm text-stone-600">{o.description}</p><p className="mt-2 text-xs font-black">{o.isActive===false?'Hidden':'Visible'}</p><div className="mt-4 flex gap-2"><button onClick={()=>edit(o)} className="rounded-xl bg-blush px-3 py-2 text-xs font-black text-brown">Edit</button><button onClick={()=>remove(o._id)} className="rounded-xl bg-red-50 px-3 py-2 text-xs font-black text-red-700">Delete</button></div></div>)}</div>}</section>; }
