/**
 * File name: src/admin/AdminServices.jsx
 * Purpose: Service CRUD manager for salon services and prices.
 * Contains: Create/update form, service list, edit button, delete button, and refresh.
 * Used by: Route /admin/services.
 * Future edits: Change service categories, price fields, or duration defaults here.
 */
import { useState } from 'react';
import { adminApi } from '../api/adminApi';
import { useAdminResource } from '../hooks/useAdminResource';
import { money } from '../utils/format';
import AdminPageHeader from '../components/AdminPageHeader.jsx';
import FormField from '../components/FormField.jsx';
import LoadingSpinner from '../components/LoadingSpinner.jsx';
const blank={name:'',category:'Threading',price:'',duration:15,description:'',isActive:true};
export default function AdminServices(){ const {data,loading,refresh}=useAdminResource(adminApi.services); const [form,setForm]=useState(blank); const [editing,setEditing]=useState(null); async function save(e){ e.preventDefault(); const payload={...form,price:Number(form.price),duration:Number(form.duration),isActive:!!form.isActive}; if(editing) await adminApi.updateService(editing,payload); else await adminApi.createService(payload); setForm(blank); setEditing(null); refresh(); } function edit(s){ setEditing(s._id); setForm({name:s.name||'',category:s.category||'',price:s.price||'',duration:s.duration||15,description:s.description||'',isActive:s.isActive!==false}); } async function remove(id){ if(confirm('Delete this service?')){ await adminApi.deleteService(id); refresh(); } } return <section><AdminPageHeader title="Services" subtitle="Add, edit, or remove public service cards and prices."/><form onSubmit={save} className="mb-6 grid gap-4 rounded-3xl border border-blush bg-white p-5 shadow-soft md:grid-cols-2"><FormField label="Service Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><FormField label="Category" value={form.category} onChange={e=>setForm({...form,category:e.target.value})} required/><FormField label="Price" type="number" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/><FormField label="Duration Minutes" type="number" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/><FormField as="textarea" label="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="min-h-24 md:col-span-2"/><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active</label><div className="flex gap-2 md:justify-end"><button className="rounded-2xl bg-brown px-5 py-3 font-black text-white">{editing?'Update Service':'Add Service'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(blank)}} className="rounded-2xl bg-stone-100 px-5 py-3 font-black text-brown">Cancel</button>}</div></form>{loading?<LoadingSpinner/>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{data.map(s=><div key={s._id} className="rounded-3xl border border-blush bg-white p-5 shadow-soft"><p className="text-xs font-black uppercase text-rose">{s.category}</p><h3 className="mt-2 text-xl font-black text-brown">{s.name}</h3><p className="mt-1 font-black text-gold">{money(s.price)} · {s.duration||15} min</p><p className="mt-2 text-sm text-stone-600">{s.description}</p><div className="mt-4 flex gap-2"><button onClick={()=>edit(s)} className="rounded-xl bg-blush px-3 py-2 text-xs font-black text-brown">Edit</button><button onClick={()=>remove(s._id)} className="rounded-xl bg-red-50 px-3 py-2 text-xs font-black text-red-700">Delete</button></div></div>)}</div>}</section>; }
